### ISSUE TITLE
多GPU训练，模型和参数字典不匹配

### ISSUE THREAD

**Issue by cheny00** [yunfan1202/Delving-into-Crispness#1]
你好朋友，我对你做的标签噪声抑制很感兴趣。正在拜读你的文章和学习你的工程。但是关于“To test with pre-trained PiDiNet model, simply run:”步骤执行时出现了问题，对此我毫无头绪。朋友能否指教一下，谢谢。

error
![image](https://github.com/yunfan1202/Delving-into-Crispness/assets/93637713/d691504e-c1e3-4950-b93b-0cb5ce73adda)

**Comment by yunfan1202** [comment]
感谢支持，我刚也搜了一下，你确定本机的显卡没问题吗，可以参考
https://github.com/pytorch/pytorch/issues/2150，
https://blog.csdn.net/sazass/article/details/116615028
多试试，要么至少先不use_cuda，试试cpu版本确认代码没问题（我本机是没问题的）

**Comment by cheny00** [comment]
感谢回复，GPU的明天我再试试。
以下是否为CPU修改的正确方式？如果是，将出现模型参数不匹配情况，该如何解决呢。

修改参数
![image](https://github.com/yunfan1202/Delving-into-Crispness/assets/93637713/5e54f911-f43a-48c9-ade8-9a19c82ff509)

state_dict 加载权值不匹配，如何处理呢？
![image](https://github.com/yunfan1202/Delving-into-Crispness/assets/93637713/1bac11bd-ce6f-4b78-a4a9-67b8b62fd467)

**Comment by yunfan1202** [comment]
晚上我又验证了一遍，确实没问题。
你这个截图里可以很明显看出来，load进来的state_dict里的所有key都正好多了个“module. ”，导致对不上。
实在不行，可以直接把所有key里的“module. ”去掉再load

**Comment by cheny00** [comment]
今天下午有空看了一下，目前已经解决，CPU和GPU都可以调通了

方法如下
model.load_state_dict(checkpoint['state_dict'])
改，
model.load_state_dict(checkpoint['state_dict'],strict=False)

感谢博主的解答，希望后面能进一步交流
