### ISSUE TITLE
你好，你可以提供你处理好的标签吗

### ISSUE THREAD

**Issue by yx-yyds** [yunfan1202/Delving-into-Crispness#2]

**Comment by yunfan1202** [comment]
可以直接用代码对训练集进行处理，当然也可以直接下载[BSDS](https://github.com/yunfan1202/Delving-into-Crispness/releases/download/datasets/BSDS_refine.zip) and [BIPED](https://github.com/yunfan1202/Delving-into-Crispness/releases/download/datasets/BIPED_refine.zip).
