### ISSUE TITLE
AC值计算问题

### ISSUE THREAD

**Issue by yx-yyds** [yunfan1202/Delving-into-Crispness#5]
计算AC时不是应该使用这样的图片吗
![image](https://github.com/yunfan1202/Delving-into-Crispness/assets/129817552/63d54876-6327-49b6-b9c5-4238f035d9ad)
为什么你们会使用
![image](https://github.com/yunfan1202/Delving-into-Crispness/assets/129817552/6c4afd3c-091c-4a28-9eb8-ef994873d292)
第一张像素对应的黑色表示非边缘,RGB值为0，白色对应边缘，RGB值为1，与模型的预测概率值对应，而第二张图片刚好相反，如果使用第二张图片计算AC，使用非极大值抑制处理后的结果如下，边缘反而变粗了，明显不对啊。
![image](https://github.com/yunfan1202/Delving-into-Crispness/assets/129817552/0615e3d6-de98-43cb-bda0-bc00284f3320)

**Comment by yunfan1202** [comment]
您好，可以关注一下eval_crispness.m里面的“is_edge_white = false;”相关的代码，如果边缘是黑色的，背景是白色的，就还是设为false就好，反之亦然。

**Comment by yx-yyds** [comment]
好的，谢谢
